version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/git" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
